---
title: Spacetime variograms
date: "`r lubridate::today()`"
output: html_document
---

```{r, echo=FALSE,message=FALSE,warning=FALSE}
rm(list=objects())
library("gstat")
library("sp")
library("spacetime")
library("vroom")
library("sf")
library("tidyverse")
library("purrr")
library("tidyverse")

readRDS("../archivio/gadm36_ITA_1_sf_originale_senzaIsolette.rds")->italia

italia %>%
  filter(NAME_1 %in% c("Piemonte","Lombardia","Veneto","Emilia-Romagna","Friuli-Venezia Giulia"))->Pianura

st_transform(Pianura,crs=32632)->Pianura
  
MESE<-1

purrr::map(1:12,.f=function(MESE){

vroom(glue::glue("datiConResiduiPerVariogrammiSpazioTemporali{MESE}.csv"),delim=";",col_names = TRUE) %>%
  mutate(yymmdd=as.Date(yymmdd)) %>%
  arrange(yymmdd)->dati

dati[!duplicated(dati$id_centralina),]->puntiStazioni
st_as_sf(puntiStazioni,coords=c("x","y"),crs=32632)->puntiStazioni
st_intersection(puntiStazioni,Pianura)->INTER

#dati[dati$id_centralina %in% INTER$id_centralina,]->subDati #se vogliamo solo dati Pianura
dati->subDati

as.data.frame(subDati)->subDati
stConstruct(x=subDati,space=c("x","y"),time="yymmdd",SpatialObj = SpatialPoints(subDati[,c("x","y")]))->STFDF_pm10
as(STFDF_pm10,"STFDF")->STFDF_pm10
variogram(lpm10~1,STFDF_pm10,width=50000,cutoff=250000,tlags=0:7)->myVariogram
variogram(lresidual~1,STFDF_pm10,width=50000,cutoff=250000,tlags=0:7)->myVariogramResiduals

myVariogram$dati<-"observations"
myVariogramResiduals$dati<-"residuals"

bind_rows(myVariogram,myVariogramResiduals)->dfVariogramma
 
dfVariogramma %>%
  mutate(id2=str_replace(id,"lag","")) %>%
  mutate(id2=str_replace(id2,"$"," days")) %>%
  mutate(id2=case_when(id2=="1 days"~"1 day",
                       TRUE~id2))->dfVariogramma

dfVariogramma$mm<-MESE

dfVariogramma

}) %>% reduce(.f=bind_rows)->finale

finale %>%
  mutate(mese=month.name[mm]) %>%
  mutate(mese=factor(mese,levels = month.name,ordered = TRUE,labels = month.name))->finale

write_delim(finale,"datiVariogrammiMensili.csv",delim=";",col_names = TRUE)
```

Variogrammi spazio-temporali costruiti con le librerie spacetime e gstat. I variogrammi mettono in evidenza che il modello cattura la struttura di correlazione spazio-temporale dei dati.

### Andamento mensile variogramma (log-pm10, residui modello)

```{r esempio1,echo=FALSE,fig.height=10,fig.width=8}
#grafico tutti mesi, con residui insieme a valori osservati
ggplot(data=finale)+
  geom_line(aes(x=spacelag,y=gamma,colour=id2,lty=dati))+
  xlab("distance (km)")+
  ylab("semivariance")+
  facet_wrap(~mese,scales = "free_y",ncol = 3)+
  scale_x_continuous(breaks =seq(0,225000,by=25000),labels=seq(0,225,by=25))+
  scale_colour_viridis_d(name="Time lag")+
  scale_linetype_discrete(name="Data")+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())
```

### Variogramma mese gennaio 2015 (log-pm10, residui modello)

```{r esempio2}
#grafico solo per un mese
ggplot(data=finale %>% filter(mm==1))+
  geom_line(aes(x=spacelag,y=gamma,colour=id2,lty=dati))+
  xlab("distance (km)")+
  ylab("semivariance")+
  #facet_wrap(~mm,scales = "free_y",ncol = 3)+
  scale_x_continuous(breaks =seq(0,225000,by=25000),labels=seq(0,225,by=25))+
  scale_colour_viridis_d(name="Time lag")+
  scale_linetype_discrete(name="Data")+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())
```

### Variogramma mese gennaio 2015 (log-pm10, residui modello). Altro esempio.

```{r esempio3}
#grafico solo per un mese, distinguendo i grafici residui/osservazioni
ggplot(data=finale %>% filter(mm==1))+
  geom_line(aes(x=spacelag,y=gamma,colour=id2))+
  xlab("distance (km)")+
  ylab("semivariance")+
  facet_wrap(~dati,scales = "free_y",ncol = 1)+
  scale_x_continuous(breaks =seq(0,225000,by=25000),labels=seq(0,225,by=25))+
  scale_colour_viridis_d(name="Time lag")+
  scale_linetype_discrete(name="Data")+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())
```
