---
title: Risultati modello PM10, 2015
date: "`r lubridate::today()`"
---

Sintesi dei risultati del modello definitivo. Il modello e' stato fatto girare per tutti e i 12 mesi del 2015 utilizzando la formula qui di seguito riportata.

## Esempio di mesh per il paper

[Mesh per il paper, colori da rivedere](./mesh.html)

## Formula definitva modello

```{r formula,include=FALSE}
# Fixed effects
lpm10~Intercept+dust+aod550.s+log.pbl00.s+log.pbl12.s+sp.s+t2m.s+tp.s+ptp.s+q_dem.s+i_surface.s+d_a1.s-1->myformula

# Random effects
update(myformula,.~.+f(id_centralina,model="iid")+f(i,model=spde,group = i.group,control.group = list(model="ar1",hyper=list(theta=theta_hyper))))->myformula

```

`r as.character(myformula)`

***

## Dati di input

[Descrizione del dataset di dati giornalieri di PM10](./descrizioneDatiInput.html)

## Dati di output

[Descrizione dei dati di output ricavati facendo girare i modelli con tutte le stazioni](./descriviDati.html)

In questa pagina viene riportata la distribuzione dei valori previsti interpolati, ricavati dalle mappe rasters.

## Fixed effects

[Posterior means, CI & co.](./covariate.html). 

[Monthly posterior marginal distributions](./covariateGrafici.html). Grafici dell'andamento mensile delle distribuzioni marginali a posteriori.

## Hyperparams

[Iperparametri del modello](./hyper.html)


## Risultati Validazione (OpenAir output)

[Output scores from OpenAir R package](./performancepm10.html). Primi risultati forniti da Giorgio utilizzando OpenAir.

[Altri risultati validazione prodotti da Guido](./elaboraRisultati.html)

[Altri risultati validazione prodotti da Guido: diagrammi di Taylor non normalizzati](./elaboraRisultati2.html)

- *Verificare quali di questi scores coincidono con quelli dell'articolo di Michela*
- *Gli scores sono stati calcolati distinguendo tra training e validation dataset?*

## Esempio di file gif per il mese di Gennaio

[Filmato dell'andamento giornaliero del PM10](./videoMappa.html). Attenzione: nel file gif la scala rimane sempre fissa al massimo valore osservato (risolvere questo problema!). Il mese si chiude con un evento di dust visibile in Sicilia.

## INdipendenza dei residui

[Variogrammi spazio temporali](./disegnaVariogramma.html)

## Eventi di dust

Le palette dei colori delle mappe INLA sono quelli del package "scico".

[Evento del 4 maggio](./evento_4maggio.html)

[Evento dell'11 giugno](./evento_11giugno.html)

## Mappa probabilita' di superamento (PM10 > 50 microgrammi)

[Esempio mappa del 26 gennaio](./mosaic.html)

## Esposizione della popolazione (valori per regione)

[Valori di esposizione rispetto alla mediana](./MedianaEsposizioneRegionali.html)

[Valori di esposizione rispetto al percentile 90.4](./Percentile90.4EsposizioneRegionali.html)

[Valori di esposizione rispetto al percentile 99.2](./Percentile99.2EsposizioneRegionali.html)

## Esposizione della popolazione (valori per zona)

[Valori di esposizione rispetto alla mediana](./MedianaEsposizioneZone.html)

[Valori di esposizione rispetto al percentile 90.4](./Percentile90.4EsposizioneZone.html)

[Valori di esposizione rispetto al percentile 99.2](./Percentile99.2EsposizioneZone.html)